### ISSUE TITLE
[Question] about redis

### ISSUE THREAD

**Issue by Renz0810** [Swofty-Developments/HypixelSkyBlock#119]
when i use redis cloud i got this error.
(Cloud url https://aiven.io)

net.swofty.loader.SkyBlock.main() INFO: Initializing proxy support...
Exception in thread "main" java.lang.NumberFormatException: For input string: "AVNS_aqqZHmdFe-PLfk3qfqf@redis-39ce5914-atlaster-7a0f.a.aivencloud.com"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:662)
        at java.base/java.lang.Integer.parseInt(Integer.java:778)
        at net.swofty.redisapi.api.RedisAPI.generateInstance(RedisAPI.java:45)
        at net.swofty.redisapi.api.RedisAPI.generateInstance(RedisAPI.java:88)
        at net.swofty.proxyapi.ProxyAPI.<init>(ProxyAPI.java:15)
        at net.swofty.loader.SkyBlock.main(SkyBlock.java:106)

**Comment by Swofty-Developments** [comment]
Will patch this tomorrow
