### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Renz0810** [Swofty-Developments/HypixelSkyBlock#137]
I enter velocity-secret correctly in resource.json, but I get a message that I cannot communicate with the Proxy server.

**To Reproduce**
Just start it up.

**Log**
-velocity-
[08:55:01 INFO]: VILLAGE: []
[08:55:01 INFO]: ISLAND: []
[08:55:01 INFO]: VILLAGE: []
[08:55:02 INFO]: ISLAND: []
[08:55:02 INFO]: VILLAGE: []
[08:55:02 INFO]: ISLAND: []
[08:55:02 INFO]: VILLAGE: [mini1L (b6a7d868-4fc1-4557-b11c-c78ff05a0bbb)]
[08:55:03 INFO]: Server b6a7d868-4fc1-4557-b11c-c78ff05a0bbb is offline! Removing from list...
[08:55:03 INFO]: Ping was sent at 1711151702712 and was not received at 1711151703115 (403ms)
[08:55:03 INFO]: ISLAND: []
[08:55:03 INFO]: VILLAGE: []
[08:55:03 INFO]: ISLAND: []
[08:55:03 INFO]: VILLAGE: []
[08:55:04 INFO]: ISLAND: []
[08:55:04 INFO]: VILLAGE: []
[08:55:04 INFO]: ISLAND: []
[08:55:04 INFO]: VILLAGE: []

-game server-
org.json.JSONException: JSONObject["pterodactyl-mode"] not found.
        at org.json.JSONObject.get(JSONObject.java:596)
        at net.swofty.commons.Configuration.getOrDefault(Configuration.java:37)
        at net.swofty.loader.SkyBlock.main(SkyBlock.java:53)
2024-03-23 08:58:20 [main] net.swofty.loader.SkyBlock.lambda$main$1() INFO: Found TypeLoader: ISLAND
2024-03-23 08:58:23 [main] net.swofty.types.generic.SkyBlockGenericLoader.initialize() INFO: All songs have been found, starting song service for this instance.
2024-03-23 08:58:23 [main] net.swofty.type.island.TypeIslandLoader.onInitialize() INFO: TypeIslandLoader initialized!
2024-03-23 08:58:23 [main] net.swofty.loader.SkyBlock.main() INFO: Initializing proxy support...
2024-03-23 08:58:24 [] net.swofty.loader.SkyBlock.lambda$main$3() ERROR: Service AUCTION_HOUSE is not online!
2024-03-23 08:58:24 [Thread-3] net.swofty.loader.SkyBlock.lambda$main$6() ERROR: Couldn't connect to proxy. Shutting down...

-screen shot-

![スクリーンショット (26)](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/163102620/c69bbf1d-d71a-43cc-adf9-4a609164571b)
![スクリーンショット (27)](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/163102620/a8955708-288d-4cae-9982-5ac0e3de1336)

**Comment by Renz0810** [comment]
sorry for bad english

**Comment by Swofty-Developments** [comment]
Hey, you are using a mismatched version of the Game Server and the `resources.json` found [here](https://github.com/Swofty-Developments/HypixelSkyBlock/blob/a9e3941d37520dd1d0fb56185e9c002433c6be73/configuration/resources.json#L6). Update your resources.json accordingly and it should turn on.

**Comment by Renz0810** [comment]
Not fixed :(

**Comment by Renz0810** [comment]
can u give me ur server files?

**Comment by Renz0810** [comment]
May I have your server files?

**Comment by Swofty-Developments** [comment]
What is the ping from your Redis to your servers? My server files are whats on the GitHub, I use the configuration folder on the Git.

**Comment by Renz0810** [comment]
How to check Redis ping?

**Comment by Swofty-Developments** [comment]
Ping the hostname of your Redis from your machine

**Comment by Renz0810** [comment]
Sorry.
I don't understand what you mean.
Could you check my server files instead?

https://www.mediafire.com/file/p1pbb0grksqikdg/SkyBlock+minestom.zip/file

**Comment by Swofty-Developments** [comment]
The issue wouldn't be an issue with your files, it's probably related to the speed of your Redis server

**Comment by Renz0810** [comment]
ok i check it later.
Thank you for nice support

**Comment by Renz0810** [comment]
what is mean this?

2024-03-23 12:01:06 [main] net.swofty.loader.SkyBlock.main() INFO: Initializing proxy support...
redis.clients.jedis.exceptions.JedisConnectionException: Failed to create socket.
        at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:116)
        at redis.clients.jedis.Connection.connect(Connection.java:180)
        at redis.clients.jedis.Connection.initializeFromClientConfig(Connection.java:338)
        at redis.clients.jedis.Connection.<init>(Connection.java:53)
        at redis.clients.jedis.Jedis.<init>(Jedis.java:214)
        at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:181)
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223)
        at redis.clients.jedis.util.Pool.getResource(Pool.java:34)
        at redis.clients.jedis.JedisPool.getResource(JedisPool.java:364)
        at net.swofty.redisapi.api.RedisAPI.lambda$startListeners$2(RedisAPI.java:137)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.net.UnknownHostException: redis-14e94864-atlasrpg2023-3f05.a.aivencloud.com
        at java.base/java.net.InetAddress$CachedLookup.get(InetAddress.java:988)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:1191)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1818)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1688)
        at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:58)        at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:87)
        ... 12 more
Exception in thread "main" net.swofty.redisapi.exceptions.MessageFailureException: Failed to send message to redis
        at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:116)
        at redis.clients.jedis.Connection.connect(Connection.java:180)
        at redis.clients.jedis.Connection.initializeFromClientConfig(Connection.java:338)
        at redis.clients.jedis.Connection.<init>(Connection.java:53)
        at redis.clients.jedis.Jedis.<init>(Jedis.java:214)
        at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:181)
        at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298)
        at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223)
        at redis.clients.jedis.util.Pool.getResource(Pool.java:34)
        at redis.clients.jedis.JedisPool.getResource(JedisPool.java:364)
        at net.swofty.redisapi.api.RedisAPI.publishMessage(RedisAPI.java:182)
        at net.swofty.proxyapi.redis.RedisMessage.sendMessageService(RedisMessage.java:55)
        at net.swofty.proxyapi.ProxyService.isOnline(ProxyService.java:17)
        at net.swofty.loader.SkyBlock.lambda$main$4(SkyBlock.java:126)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at net.swofty.loader.SkyBlock.main(SkyBlock.java:125)

**Comment by Swofty-Developments** [comment]
Your Redis server isn't even running

**Comment by Renz0810** [comment]
Is it possible to create a server file on your PC and have it sent to us?

**Comment by Renz0810** [comment]
Is it possible to create a server file on your PC and have it sent to me?

**Comment by Swofty-Developments** [comment]
> Is it possible to create a server file on your PC and have it sent to me?

What do you mean create a server file?

**Comment by Renz0810** [comment]
yeah

**Comment by Renz0810** [comment]
Fixed. Thank you for nice support
