### ISSUE TITLE
[BUG] No Drops When Breaking Blocks On Island

### ISSUE THREAD

**Issue by JustAiden9** [Swofty-Developments/HypixelSkyBlock#346]
**Describe the bug**
When I try to break any blocks on the island nothing drops so it is impossible to complete the first mission without using /completemissionset GETTING_STARTED. 

**To Reproduce**
1. Go on versions '1.8.9-1.21'
2. Join server
3. Try to break a block, for example dirt, grass, or wood.

**Expected behavior**
The ability to get the block you broke.

**Screenshots**
![Screenshot 2024-06-23 083517](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/104693998/153484d4-edd0-4e31-89e7-9722186dd30e)

**Comment by JustAiden9** [comment]
When I try to break the block I get this error below, I attached the full log:

PS C:\Users\aiden\OneDrive\Desktop\SB Server\game_server> java --enable-preview -jar SkyBlockCore.jar ISLAND
2024-06-23 08:54:44 [main] net.swofty.loader.SkyBlock.lambda$main$1() INFO: Found TypeLoader: THE_FARMING_ISLANDS
2024-06-23 08:54:44 [main] net.swofty.loader.SkyBlock.lambda$main$1() INFO: Found TypeLoader: ISLAND
2024-06-23 08:54:46 [main] net.swofty.types.generic.SkyBlockGenericLoader.initialize() ERROR: Not all songs have been found, song service will not start for this instance.
2024-06-23 08:54:47 [main] net.swofty.type.island.TypeIslandLoader.onInitialize() INFO: TypeIslandLoader initialized!
2024-06-23 08:54:47 [main] net.swofty.loader.SkyBlock.main() INFO: Initializing proxy support...
2024-06-23 08:54:47 [Thread-2] net.minestom.server.ServerProcessImpl.start() INFO: Starting SkyBlock server.
2024-06-23 08:54:48 [Thread-2] net.minestom.server.ServerProcessImpl.start() INFO: SkyBlock server started successfully.
2024-06-23 08:54:48 [Thread-2] net.swofty.loader.SkyBlock.lambda$main$4() INFO: Started server on port 20000 in 3401ms
2024-06-23 08:54:48 [Thread-2] net.swofty.loader.SkyBlock.lambda$main$4() INFO: Server Type: ISLAND
2024-06-23 08:54:48 [Thread-2] net.swofty.loader.SkyBlock.lambda$main$4() INFO: Internal ID: 24595ae0-2619-46bc-837a-807e53aa7dc6
2024-06-23 08:55:00 [Ms-worker-1] net.swofty.types.generic.SkyBlockGenericLoader.lambda$initialize$30() INFO: Received new player: JustAiden (f539d1d0-d861-45cf-8c16-a6400e6b84e1)
2024-06-23 08:55:00 [ForkJoinPool.commonPool-worker-14] net.swofty.types.generic.event.actions.player.data.ActionPlayerDataLoad.run() INFO: New player joined: JustAiden...
2024-06-23 08:55:01 [] net.swofty.types.generic.event.actions.player.data.ActionPlayerDataSpawn.run() INFO: Loading player data for JustAiden...
2024-06-23 08:55:11 [Ms-TickScheduler] net.swofty.types.generic.event.SkyBlockEventHandler.lambda$register$3() INFO: Exception occurred while running event Method with event type PlayerBlockBreakEvent
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:115)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at net.swofty.types.generic.event.SkyBlockEventHandler.runEvent(SkyBlockEventHandler.java:156)
        at net.swofty.types.generic.event.SkyBlockEventHandler.lambda$register$3(SkyBlockEventHandler.java:106)
        at net.minestom.server.event.EventListener$Builder$1.run(EventListener.java:151)
        at net.minestom.server.event.EventNodeImpl$Handle.callListener(EventNodeImpl.java:491)
        at net.minestom.server.event.EventNodeImpl$Handle.lambda$listenersConsumer$9(EventNodeImpl.java:429)
        at net.minestom.server.event.EventNodeImpl$Handle.lambda$createConsumer$5(EventNodeImpl.java:394)
        at net.minestom.server.event.EventNodeImpl$Handle.lambda$createConsumer$5(EventNodeImpl.java:402)
        at net.minestom.server.event.EventNodeImpl$Handle.call(EventNodeImpl.java:327)
        at net.minestom.server.event.EventNode.call(EventNode.java:190)
        at net.minestom.server.event.EventDispatcher.call(EventDispatcher.java:10)
        at net.minestom.server.instance.InstanceContainer.breakBlock(InstanceContainer.java:234)
        at net.minestom.server.instance.SharedInstance.breakBlock(SharedInstance.java:41)
        at net.minestom.server.instance.Instance.breakBlock(Instance.java:202)
        at net.minestom.server.listener.PlayerDiggingListener.breakBlock(PlayerDiggingListener.java:177)
        at net.minestom.server.listener.PlayerDiggingListener.finishDigging(PlayerDiggingListener.java:112)
        at net.minestom.server.listener.PlayerDiggingListener.playerDiggingListener(PlayerDiggingListener.java:46)
        at net.minestom.server.listener.manager.PacketListenerManager.lambda$setPlayListener$2(PacketListenerManager.java:163)
        at net.minestom.server.listener.manager.PacketListenerManager.processClientPacket(PacketListenerManager.java:132)
        at net.minestom.server.entity.Player.lambda$interpretPacketQueue$12(Player.java:2128)
        at org.jctools.queues.MpscUnboundedXaddArrayQueue.drain(MpscUnboundedXaddArrayQueue.java:312)
        at net.minestom.server.entity.Player.interpretPacketQueue(Player.java:2128)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
        at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
        at net.minestom.server.network.ConnectionManager.tick(ConnectionManager.java:368)
        at net.minestom.server.ServerProcessImpl$TickerImpl.tick(ServerProcessImpl.java:375)
        at net.minestom.server.thread.TickSchedulerThread.run(TickSchedulerThread.java:29)
Caused by: java.lang.NullPointerException: Cannot invoke "net.swofty.types.generic.region.mining.MineableBlock.getFortuneType()" because "mineableBlock" is null
        at net.swofty.types.generic.event.actions.player.region.ActionRegionBlockBreak.run(ActionRegionBlockBreak.java:73)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 27 more
