### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by uk-twistic2** [Swofty-Developments/HypixelSkyBlock#350]
Loading SkyblockCore.jar ISLAND

```
root@Debian-bookworm-latest-amd64-base /home/tcagame_svc13/admin/13 # java -jar SkyBlockCore.jar ISLAND
2024-07-01 22:18:38 [main] net.swofty.loader.SkyBlock.lambda$main$1() INFO: Found TypeLoader: THE_FARMING_ISLANDS
2024-07-01 22:18:38 [main] net.swofty.loader.SkyBlock.lambda$main$1() INFO: Found TypeLoader: ISLAND
2024-07-01 22:18:38 [main] net.swofty.loader.SkyBlock.lambda$main$1() INFO: Found TypeLoader: HUB
2024-07-01 22:18:39 [main] net.swofty.types.generic.SkyBlockGenericLoader.initialize() INFO: All songs have been found, starting song service for this instance.
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant net.swofty.commons.ServerType.
        at java.base/java.lang.Enum.valueOf(Enum.java:293)
        at net.swofty.commons.ServerType.valueOf(ServerType.java:4)
        at net.swofty.types.generic.data.mongodb.RegionDatabase.getAllRegions(RegionDatabase.java:99)
        at net.swofty.types.generic.region.SkyBlockRegion.cacheRegions(SkyBlockRegion.java:175)
        at net.swofty.types.generic.SkyBlockGenericLoader.initialize(SkyBlockGenericLoader.java:228)
        at net.swofty.loader.SkyBlock.main(SkyBlock.java:89)
```

**Comment by Swofty-Developments** [comment]
You have not correctly imported your regions into MongoDB
