### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LootingVI** [Swofty-Developments/HypixelSkyBlock#381]
[00:54:35 ERROR]: Exception in thread "" java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "pk" is null
[00:54:35 ERROR]:       at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328)
[00:54:35 ERROR]:       at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242)
[00:54:35 ERROR]:       at net.swofty.velocity.gamemanager.BalanceConfigurations.getServerFor(BalanceConfigurations.java:27)
[00:54:35 ERROR]:       at net.swofty.velocity.SkyBlockVelocity.lambda$onServerCrash$9(SkyBlockVelocity.java:216)
[00:54:35 ERROR]:       at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)

**Comment by Swofty-Developments** [comment]
What caused it?

**Comment by LootingVI** [comment]
> What caused it?

Player join

**Comment by Lexxxy123** [comment]
> What caused it?

well how do we use your core in a hosting? any idea/? or  tutorial? please?

**Comment by Swofty-Developments** [comment]
> > What caused it?
> 
> well how do we use your core in a hosting? any idea/? or tutorial? please?

You’d need the hosting to allow for you to change startup arguments.



> > What caused it?
> 
> Player join

I am not able to replicate this, please join the discord so we can talk further.
