### ISSUE TITLE
[BUG] Crafting error

### ISSUE THREAD

**Issue by TRLKO** [Swofty-Developments/HypixelSkyBlock#49]
**Describe the bug**

At the very beginning, I respawn on an island and do the mission to collect a tree and then build a workbench. During the creation, I put the wood in the inventory and instead of taking out the board, a window opens where there is a full workbench (the kind where you open a workbench and not a small one like there is in the inventory). I make planks and from them this workbench. When I want to take it out, I take it out without a problem, but an error appears in the console.

**To Reproduce**

1. Start from scratch on island
2. Destory tree
3. In workbrnch change wood to planks
4. This planks change to workbench
5. When you get out this workbench from workbench error apear in console

**Error**

```
2024-01-16 18:52:50 [Ms-Tick-0] net.swofty.types.generic.event.SkyBlockEvent.lambda$register$2() INFO: Exception occurred while running event ActionPlayerInventoryClick with event type InventoryPreClickEvent
java.lang.NullPointerException: Cannot invoke "net.swofty.types.generic.item.ItemType.equals(Object)" because the return value of "net.swofty.types.generic.item.MaterialQuantifiable.getMaterial()" is null
        at net.swofty.types.generic.item.impl.recipes.ShapedRecipe.consume(ShapedRecipe.java:85)
        at net.swofty.types.generic.gui.inventory.inventories.sbmenu.GUICrafting$1.run(GUICrafting.java:132)
        at net.swofty.types.generic.event.actions.player.gui.ActionPlayerInventoryClick.run(ActionPlayerInventoryClick.java:86)
        at net.swofty.types.generic.event.SkyBlockEvent.lambda$register$2(SkyBlockEvent.java:96)
        at net.minestom.server.event.EventListener$Builder$1.run(EventListener.java:151)
        at net.minestom.server.event.EventNodeImpl$Handle.callListener(EventNodeImpl.java:491)
        at net.minestom.server.event.EventNodeImpl$Handle.lambda$listenersConsumer$9(EventNodeImpl.java:429)
        at net.minestom.server.event.EventNodeImpl$Handle.lambda$createConsumer$5(EventNodeImpl.java:394)
        at net.minestom.server.event.EventNodeImpl$Handle.lambda$createConsumer$5(EventNodeImpl.java:402)
        at net.minestom.server.event.EventNodeImpl$Handle.call(EventNodeImpl.java:327)
        at net.minestom.server.event.EventNode.call(EventNode.java:190)
        at net.minestom.server.event.EventDispatcher.call(EventDispatcher.java:10)
        at net.minestom.server.inventory.click.InventoryClickProcessor.startCondition(InventoryClickProcessor.java:430)
        at net.minestom.server.inventory.click.InventoryClickProcessor.leftClick(InventoryClickProcessor.java:37)
        at net.minestom.server.inventory.Inventory.leftClick(Inventory.java:221)
        at net.minestom.server.listener.WindowListener.clickWindowListener(WindowListener.java:41)
        at net.minestom.server.listener.manager.PacketListenerManager.processClientPacket(PacketListenerManager.java:90)
        at net.minestom.server.entity.Player.lambda$interpretPacketQueue$18(Player.java:1950)
        at org.jctools.queues.MpscUnboundedXaddArrayQueue.drain(MpscUnboundedXaddArrayQueue.java:312)
        at net.minestom.server.entity.Player.interpretPacketQueue(Player.java:1950)
        at net.minestom.server.entity.Player.update(Player.java:387)
        at net.minestom.server.entity.Entity.tick(Entity.java:562)
        at net.minestom.server.thread.TickThread.tick(TickThread.java:74)
        at net.minestom.server.thread.TickThread.run(TickThread.java:49)

```
![image](https://github.com/Swofty-Developments/HypixelSkyBlock/assets/16487891/88918090-b328-482d-aef5-641d727e6eaf)

**Comment by Swofty-Developments** [comment]
I’ve been able to replicate the issue and will push a fix shortly.

**Comment by Swofty-Developments** [comment]
Issue has been fixed with latest commit
